name: MLflow Training Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    env:
      # Default; will be overwritten if practice/ exists
      PROJECT_ROOT: ${{ github.workspace }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Project Root (with or without practice/)
        id: detect-root
        run: |
          set -eux
          if [ -d "${{ github.workspace }}/practice" ]; then
            echo "PROJECT_ROOT=${{ github.workspace }}/practice" >> $GITHUB_ENV
          else
            echo "PROJECT_ROOT=${{ github.workspace }}" >> $GITHUB_ENV
          fi

      - name: Show Directory Tree (debug)
        run: |
          set -eux
          echo "Using PROJECT_ROOT=$PROJECT_ROOT"
          ls -R $PROJECT_ROOT

      - name: Create Docker Network
        run: |
          docker network create mlflow-net || echo "Network already exists"

      # ---------- Build MLflow Server Image ----------
      - name: Build MLflow Server Image
        run: |
          docker build -t mlflow-server -f $PROJECT_ROOT/mlflow-server/Dockerfile $PROJECT_ROOT/mlflow-server

      - name: Ensure mlruns dir exists
        run: |
          mkdir -p $PROJECT_ROOT/mlflow-server/mlruns

      - name: Run MLflow Server Container
        run: |
          docker run -d \
            --name mlflow-server \
            --network mlflow-net \
            -p 5050:5000 \
            -v $PROJECT_ROOT/mlflow-server/mlruns:/mlflow/mlruns \
            mlflow-server

      # ---------- Build Training Image ----------
      - name: Build Training Image
        run: |
          docker build -t mnist-training:latest -f $PROJECT_ROOT/training/Dockerfile $PROJECT_ROOT/training

      - name: Run Training Container
        run: |
          docker run --rm \
            --network mlflow-net \
            -e MLFLOW_TRACKING_URI=http://mlflow-server:5000 \
            mnist-training:latest

      # ---------- Upload MLflow Logs ----------
      - name: Upload MLflow Logs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-logs
          path: ${{ env.PROJECT_ROOT }}/mlflow-server/mlruns
